### ISSUE TITLE
Type alias 'CompletionBlock' error

### ISSUE THREAD

**Issue by akrofrog** [MinterTeam/minter-ios-core#2]
Hi! Can't build the project. There is an issue with "HTTPClient.CompletionBlock" in APIClient.swift in Xcode11: "Type alias 'CompletionBlock' can only be used with a concrete type or generic parameter base".

**Comment by sidorov-panda** [comment]
Hello. 
Could you please specify more info, do you open workspace after installing pods in Example folder?
What swift version do you use?
Thank you
